apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # static PV는 이거 없어도 됨
  hostPath:
    path: /mnt/data/elasticsearch
  persistentVolumeReclaimPolicy: Retain