apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: flask
    app: flask
    release: prom-stack
  name: flask
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: flask
    spec:
      containers:
        - args:
            - python
            - app.py
            - --host=0.0.0.0
          image: ljs3536/shoppingmall-flask:latest
          name: flask-container
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: spring-app-config
          workingDir: /app
      restartPolicy: Always
