apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-monitor
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      io.kompose.service: springboot
  endpoints:
    - port: "8080"
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
